name = "espacofacial-site"
main = ".open-next/worker.js"
compatibility_date = "2026-01-11"
compatibility_flags = ["nodejs_compat"]

workers_dev = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
